In [10]:
def grid_traveller(m,n, d={}):
    key = (m,n)
    if m==1 and n==1:
        return 1
    if m==0 or n==0:
        return 0
    if key in d:
        return d[key]
    d[key]=grid_traveller(m-1,n,d) + grid_traveller(m,n-1,d)
    return d[key]

In [12]:
grid_traveller(2,3), grid_traveller(3,2), grid_traveller(1,1), grid_traveller(18, 18)

(3, 3, 1, 2333606220)

In [16]:
def fib(n, d={}):
    if n<=2:
        return 1
    if n in d:
        return d[n]
    d[n] = fib(n-1, d) + fib(n-2, d)
    return d[n]

In [23]:
fib(3), fib(2)

(2, 1)

In [37]:
all_alpha = "The quick brown foxes jumped over the lazy dog."
all_alpha = all_alpha.split()

In [63]:
tuple(zip(*[all_alpha[i:] for i in range(4)]))

(('The', 'quick', 'brown', 'foxes'),
 ('quick', 'brown', 'foxes', 'jumped'),
 ('brown', 'foxes', 'jumped', 'over'),
 ('foxes', 'jumped', 'over', 'the'),
 ('jumped', 'over', 'the', 'lazy'),
 ('over', 'the', 'lazy', 'dog.'))

Given an array of strings, group the anagrams together. You can return the answer in any order.

An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

Solved using hashmap

Example 1:

Input: strs = ["eat","tea","tan","ate","nat","bat"] Output: [["bat"],["nat","tan"],["ate","eat","tea"]] Example 2:

Input: strs = [""] Output: [[""]] Example 3:

Input: strs = ["a"] Output: [["a"]]

In [67]:
tuple(sorted("atc"))

('a', 'c', 't')

In [76]:
def ana(strs):
    d={}
    for eachstr in strs:
        d.setdefault(tuple(sorted(eachstr)),[]).append(eachstr)
    return d.values()

In [77]:
ana(["eat","tea","tan","ate","nat","bat"])

dict_values([['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']])

Can Sum O(m*n)

Given a target sum and a list of integers, verify whether the integers can actually match the target sum, same integers can be reused as many times as needed.

Example 1 target = 7 list = [5,4,3,7] output = True

Example 2 target = 14 list = [5,5] output = false

In [97]:
def cansum(target, ints, d={}):
    if target in d:
        return d[target]
    if target ==0:
        return True
    if target < 0:
        return False
    for i in ints:
        rem = target - i
        if cansum(rem, ints, d):
            d[target] = True
            return True
    d[target]= False
    return False

In [129]:
cansum(7, [5,4,3,7], {}), cansum(7, [2,4], {})

(True, False)

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

Solved using hashmap

Example 1:

Input: nums = [2,7,11,15], target = 9 Output: [0,1] Explanation: Because nums[0] + nums[1] == 9, we return [0, 1]. Example 2:

Input: nums = [3,2,4], target = 6 Output: [1,2] Example 3:

Input: nums = [3,3], target = 6 Output: [0,1]

In [130]:
def twosum(ls, t):
    d={}
    for i,j in enumerate(ls):
        rem = t-j
        if rem in d:
            return [d[rem],i]
        d[j]=i


In [133]:
twosum([3,3],6)

[0, 1]

Pivot Index

Given an array of integers nums, calculate the pivot index of this array.

The pivot index is the index where the sum of all the numbers strictly to the left of the index is equal to the sum of all the numbers strictly to the index's right.

If the index is on the left edge of the array, then the left sum is 0 because there are no elements to the left. This also applies to the right edge of the array.

Return the leftmost pivot index. If no such index exists, return -1.

In [138]:
def pivot(n):
    for idx,_ in enumerate(n):
        tot_sum =sum(n)
        if not idx:
            l_sum=0
            r_sum=tot_sum - n[idx]
            if l_sum == r_sum:
                return idx
        else:
            l_sum=sum(n[:idx])
            r_sum=tot_sum-n[idx]-l_sum
            if l_sum==r_sum:
                return idx
    return -1

In [139]:
pivot([1,7,3,6,5,6])

3

In [150]:
[j[0] for i,j in enumerate(dict.fromkeys([1,7,3,6,5,6]).items())]

[1, 7, 3, 6, 5]

In [169]:
def topk(ls,n):
    d={}
    res=[]
    for num in ls:
        d[num] = d.get(num,0) + 1
    d_sorted = {k:v for k,v in sorted(d.items(), key=lambda x: x[1])}
    if n>len(d_sorted):
        return d_sorted.keys()
    else:
        for i,j in enumerate((d_sorted.items())):
            if i<n:
                res.append(d_sorted[j[0]])
    return res, d_sorted, d

In [170]:
topk([1,1,1,2,2,3], 2)

([1, 2], {3: 1, 2: 2, 1: 3}, {1: 3, 2: 2, 3: 1})

[2,7,11,15], target = 9 Output: [1,2] 

In [171]:
def twosum(nums, t):
    l_idx, r_idx = 0, len(nums)-1
    while l_idx<r_idx:
        curr_sum = nums[l_idx] + nums[r_idx]
        if curr_sum>t:
            r_idx-=1
        elif curr_sum<t:
            l_idx+=1
        else:
            return [l_idx+1, r_idx+1]

In [173]:
twosum([2,3,4],  6)

[1, 3]

nums = [-1,0,1,2,-1,-4] Output: [[-1,-1,2],[-1,0,1]] 

In [243]:
def threesum(nums):
    results=[]
    nums.sort()
    
    for i,j in enumerate(nums):
        if i>0 and j==nums[i-1]:
            continue
        l_idx, r_idx = i+1,len(nums)-1
        while l_idx < r_idx:
            curr_sum = nums[l_idx] + nums[r_idx] + j
            if curr_sum > 0:
                r_idx -=1
            elif curr_sum < 0:
                l_idx +=1
            else:
                results.append([nums[l_idx], j, nums[r_idx]])
                l_idx +=1
                while nums[l_idx] == nums[l_idx-1] and l_idx < r_idx:
                    l_idx +=1
    return results

In [244]:
threesum([-1,0,1,2,-1,-4]), threesum([]), threesum([0])

([[-1, -1, 2], [0, -1, 1]], [], [])

# Linear Classifier NN

In [1]:
import torch
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the Iris dataset and split it into training and testing sets
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2, random_state=42)

# Convert the data into PyTorch tensors and normalize the features
X_train = torch.tensor(X_train).float()
X_test = torch.tensor(X_test).float()
y_train = torch.tensor(y_train)
y_test = torch.tensor(y_test)

mean = X_train.mean(dim=0)
std = X_train.std(dim=0)
X_train = (X_train - mean) / std
X_test = (X_test - mean) / std

In [10]:
# Define the linear classifier model
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=4, out_features=3),
    torch.nn.Softmax(dim=1)
)

In [12]:
# Define the loss function and the optimizer
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):  # Number of epochs
    model.train()
    optimizer.zero_grad()
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(X_train)

    # Compute and print loss
    loss = loss_fn(y_pred, y_train)
    if epoch % 10 == 0:
        print(f'Epoch: {epoch} Loss: {loss.item()}')

    # Zero gradients, perform a backward pass, and update the weights.
    loss.backward()
    optimizer.step()


Epoch: 0 Loss: 1.0061719417572021
Epoch: 10 Loss: 1.0007625818252563
Epoch: 20 Loss: 0.9955267310142517
Epoch: 30 Loss: 0.9904457926750183
Epoch: 40 Loss: 0.9855024814605713
Epoch: 50 Loss: 0.9806820750236511
Epoch: 60 Loss: 0.9759709239006042
Epoch: 70 Loss: 0.9713577032089233
Epoch: 80 Loss: 0.9668325781822205
Epoch: 90 Loss: 0.9623873829841614


In [4]:
torch.argmax(model(X_test), dim=1), y_test

(tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
         2, 2, 2, 2, 0, 0]),
 tensor([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0, 2,
         2, 2, 2, 2, 0, 0]))

In [212]:
model(X_test)[0]

tensor([0.3257, 0.3172, 0.3571], grad_fn=<SelectBackward0>)

In [175]:
import torch.nn.functional as F

# Create a random tensor
a = torch.randn(2, 3)

# Apply Softmax
F.softmax(a, dim=0)

tensor([[0.4693, 0.0385, 0.2544],
        [0.5307, 0.9615, 0.7456]])

In [177]:
a

tensor([[ 0.2747, -2.0503, -0.2131],
        [ 0.3976,  1.1685,  0.8623]])

In [186]:
import math

In [191]:
math.exp(0.2747)/sum([math.exp(i) for i in a[0]])

0.5841928744333489

In [184]:
F.softmax(a, dim=1)

tensor([[0.5842, 0.0571, 0.3587],
        [0.2104, 0.4548, 0.3348]])

# Linear Regression NN

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [15]:
# Load the diabetes dataset and split it into training and testing sets
diabetes = load_diabetes()
X_train, X_test, y_train, y_test = train_test_split(diabetes.data,
                                                    diabetes.target,
                                                    test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert the data into PyTorch tensors
X_train = torch.tensor(X_train).float()
X_test = torch.tensor(X_test).float()
y_train = torch.tensor(y_train).float().view(-1, 1)  # Reshape y_train to have 2 dimensions
y_test = torch.tensor(y_test).float().view(-1, 1)    # Reshape y_test to have 2 dimensions

In [57]:
# Define the neural network architecture
class RegressionNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RegressionNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)  # Input to hidden layer
        self.relu = nn.ReLU()                          # Activation function
        self.fc2 = nn.Linear(hidden_size, output_size) # Hidden to output layer

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

# Set the input size, hidden layer size, and output size
input_size = diabetes.data.shape[1]  # Number of input features
hidden_size = 10                     # Number of neurons in the hidden layer
output_size = 1                      # Number of output features (for regression, usually 1)

# Create the neural network
model = RegressionNN(input_size, hidden_size, output_size)

In [62]:
# Define the loss function and optimizer
criterion = nn.MSELoss()  # Mean Squared Error Loss
optimizer = optim.Adam(model.parameters(), lr=0.01)  # Adam optimizer

In [63]:
# Training loop
for epoch in range(10000):  # Number of epochs
    model.train()
    optimizer.zero_grad()   # Clear gradients
    outputs = model(X_train) # Forward pass
    loss = criterion(outputs, y_train) # Calculate loss
    loss.backward()         # Backward pass
    optimizer.step()        # Update weights

    if epoch % 100 == 0:
        print(f'Epoch [{epoch+1}/1000], Loss: {loss.item():.4f}')

Epoch [1/1000], Loss: 29863.6465
Epoch [101/1000], Loss: 18182.9512
Epoch [201/1000], Loss: 8555.9854
Epoch [301/1000], Loss: 4960.8135
Epoch [401/1000], Loss: 3728.3467
Epoch [501/1000], Loss: 2987.0435
Epoch [601/1000], Loss: 2762.5471
Epoch [701/1000], Loss: 2667.9546
Epoch [801/1000], Loss: 2621.2632
Epoch [901/1000], Loss: 2582.3611
Epoch [1001/1000], Loss: 2549.3413
Epoch [1101/1000], Loss: 2531.5759
Epoch [1201/1000], Loss: 2518.5947
Epoch [1301/1000], Loss: 2508.1697
Epoch [1401/1000], Loss: 2498.6658
Epoch [1501/1000], Loss: 2489.7092
Epoch [1601/1000], Loss: 2481.7207
Epoch [1701/1000], Loss: 2474.5342
Epoch [1801/1000], Loss: 2469.4895
Epoch [1901/1000], Loss: 2464.9402
Epoch [2001/1000], Loss: 2459.4458
Epoch [2101/1000], Loss: 2453.5969
Epoch [2201/1000], Loss: 2446.4741
Epoch [2301/1000], Loss: 2437.6755
Epoch [2401/1000], Loss: 2427.8005
Epoch [2501/1000], Loss: 2414.5803
Epoch [2601/1000], Loss: 2405.6121
Epoch [2701/1000], Loss: 2398.5171
Epoch [2801/1000], Loss: 2385.

In [34]:
model(X_test[0]), y_test[0]

(tensor([215.2087], grad_fn=<ViewBackward0>), tensor([219.]))

In [26]:
from sklearn.metrics import mean_squared_error

In [60]:
mean_squared_error(y_true=y_test, y_pred=model(X_test).detach())

2841.6616