In [10]:
def grid_traveller(m,n, d={}):
    key = (m,n)
    if m==1 and n==1:
        return 1
    if m==0 or n==0:
        return 0
    if key in d:
        return d[key]
    d[key]=grid_traveller(m-1,n,d) + grid_traveller(m,n-1,d)
    return d[key]

In [12]:
grid_traveller(2,3), grid_traveller(3,2), grid_traveller(1,1), grid_traveller(18, 18)

(3, 3, 1, 2333606220)

In [16]:
def fib(n, d={}):
    if n<=2:
        return 1
    if n in d:
        return d[n]
    d[n] = fib(n-1, d) + fib(n-2, d)
    return d[n]

In [23]:
fib(3), fib(2)

(2, 1)

In [37]:
all_alpha = "The quick brown foxes jumped over the lazy dog."
all_alpha = all_alpha.split()

In [63]:
tuple(zip(*[all_alpha[i:] for i in range(4)]))

(('The', 'quick', 'brown', 'foxes'),
 ('quick', 'brown', 'foxes', 'jumped'),
 ('brown', 'foxes', 'jumped', 'over'),
 ('foxes', 'jumped', 'over', 'the'),
 ('jumped', 'over', 'the', 'lazy'),
 ('over', 'the', 'lazy', 'dog.'))

Given an array of strings, group the anagrams together. You can return the answer in any order.

An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.

Solved using hashmap

Example 1:

Input: strs = ["eat","tea","tan","ate","nat","bat"] Output: [["bat"],["nat","tan"],["ate","eat","tea"]] Example 2:

Input: strs = [""] Output: [[""]] Example 3:

Input: strs = ["a"] Output: [["a"]]

In [67]:
tuple(sorted("atc"))

('a', 'c', 't')

In [76]:
def ana(strs):
    d={}
    for eachstr in strs:
        d.setdefault(tuple(sorted(eachstr)),[]).append(eachstr)
    return d.values()

In [77]:
ana(["eat","tea","tan","ate","nat","bat"])

dict_values([['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']])

Can Sum O(m*n)

Given a target sum and a list of integers, verify whether the integers can actually match the target sum, same integers can be reused as many times as needed.

Example 1 target = 7 list = [5,4,3,7] output = True

Example 2 target = 14 list = [5,5] output = false

In [97]:
def cansum(target, ints, d={}):
    if target in d:
        return d[target]
    if target ==0:
        return True
    if target < 0:
        return False
    for i in ints:
        rem = target - i
        if cansum(rem, ints, d):
            d[target] = True
            return True
    d[target]= False
    return False

In [129]:
cansum(7, [5,4,3,7], {}), cansum(7, [2,4], {})

(True, False)

Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

Solved using hashmap

Example 1:

Input: nums = [2,7,11,15], target = 9 Output: [0,1] Explanation: Because nums[0] + nums[1] == 9, we return [0, 1]. Example 2:

Input: nums = [3,2,4], target = 6 Output: [1,2] Example 3:

Input: nums = [3,3], target = 6 Output: [0,1]

In [130]:
def twosum(ls, t):
    d={}
    for i,j in enumerate(ls):
        rem = t-j
        if rem in d:
            return [d[rem],i]
        d[j]=i


In [133]:
twosum([3,3],6)

[0, 1]

Pivot Index

Given an array of integers nums, calculate the pivot index of this array.

The pivot index is the index where the sum of all the numbers strictly to the left of the index is equal to the sum of all the numbers strictly to the index's right.

If the index is on the left edge of the array, then the left sum is 0 because there are no elements to the left. This also applies to the right edge of the array.

Return the leftmost pivot index. If no such index exists, return -1.

In [138]:
def pivot(n):
    for idx,_ in enumerate(n):
        tot_sum =sum(n)
        if not idx:
            l_sum=0
            r_sum=tot_sum - n[idx]
            if l_sum == r_sum:
                return idx
        else:
            l_sum=sum(n[:idx])
            r_sum=tot_sum-n[idx]-l_sum
            if l_sum==r_sum:
                return idx
    return -1

In [139]:
pivot([1,7,3,6,5,6])

3

In [150]:
[j[0] for i,j in enumerate(dict.fromkeys([1,7,3,6,5,6]).items())]

[1, 7, 3, 6, 5]

In [169]:
def topk(ls,n):
    d={}
    res=[]
    for num in ls:
        d[num] = d.get(num,0) + 1
    d_sorted = {k:v for k,v in sorted(d.items(), key=lambda x: x[1])}
    if n>len(d_sorted):
        return d_sorted.keys()
    else:
        for i,j in enumerate((d_sorted.items())):
            if i<n:
                res.append(d_sorted[j[0]])
    return res, d_sorted, d

In [170]:
topk([1,1,1,2,2,3], 2)

([1, 2], {3: 1, 2: 2, 1: 3}, {1: 3, 2: 2, 3: 1})

[2,7,11,15], target = 9 Output: [1,2] 

In [171]:
def twosum(nums, t):
    l_idx, r_idx = 0, len(nums)-1
    while l_idx<r_idx:
        curr_sum = nums[l_idx] + nums[r_idx]
        if curr_sum>t:
            r_idx-=1
        elif curr_sum<t:
            l_idx+=1
        else:
            return [l_idx+1, r_idx+1]

In [173]:
twosum([2,3,4],  6)

[1, 3]

In [192]:
import torch
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the Iris dataset and split it into training and testing sets
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                    iris.target,
                                                    test_size=0.2, random_state=42)

# Convert the data into PyTorch tensors and normalize the features
X_train = torch.tensor(X_train).float()
X_test = torch.tensor(X_test).float()
y_train = torch.tensor(y_train)
y_test = torch.tensor(y_test)

mean = X_train.mean(dim=0)
std = X_train.std(dim=0)
X_train = (X_train - mean) / std
X_test = (X_test - mean) / std

# Define the linear classifier model
model = torch.nn.Sequential(
    torch.nn.Linear(in_features=4, out_features=3),
    torch.nn.Softmax(dim=1)
)


In [ ]:
torch.nn.CrossEntropyLoss?

Init signature:
torch.nn.CrossEntropyLoss(
    weight: Union[torch.Tensor, NoneType] = None,
    size_average=None,
    ignore_index: int = -100,
    reduce=None,
    reduction: str = 'mean',
    label_smoothing: float = 0.0,
) -> None
Docstring:     
This criterion computes the cross entropy loss between input logits
and target.

It is useful when training a classification problem with `C` classes.
If provided, the optional argument :attr:`weight` should be a 1D `Tensor`
assigning weight to each of the classes.
This is particularly useful when you have an unbalanced training set.

The `input` is expected to contain the unnormalized logits for each class (which do `not` need
to be positive or sum to 1, in general).
`input` has to be a Tensor of size :math:`(C)` for unbatched input,
:math:`(minibatch, C)` or :math:`(minibatch, C, d_1, d_2, ..., d_K)` with :math:`K \geq 1` for the
`K`-dimensional case. The last being useful for higher dimension inputs, such
as computing cross entropy los

In [201]:
# Define the loss function and the optimizer
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):  # Number of epochs
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(X_train)

    # Compute and print loss
    loss = loss_fn(y_pred, y_train)
    if epoch % 10 == 0:
        print(f'Epoch: {epoch} Loss: {loss.item()}')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


tensor([0.8238, 0.4491, 1.7523, 0.7523])

In [175]:
import torch.nn.functional as F

# Create a random tensor
a = torch.randn(2, 3)

# Apply Softmax
F.softmax(a, dim=0)

tensor([[0.4693, 0.0385, 0.2544],
        [0.5307, 0.9615, 0.7456]])

In [177]:
a

tensor([[ 0.2747, -2.0503, -0.2131],
        [ 0.3976,  1.1685,  0.8623]])

In [186]:
import math

In [191]:
math.exp(0.2747)/sum([math.exp(i) for i in a[0]])

0.5841928744333489

In [184]:
F.softmax(a, dim=1)

tensor([[0.5842, 0.0571, 0.3587],
        [0.2104, 0.4548, 0.3348]])